name: Deploy Coffe Frontend

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Conectar a Tailscale
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TAILSCALE_AUTH_KEY }}

      - name: Ejecutar comandos por SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: root
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script_stop: true
          fingerprint: ${{ secrets.SSH_FINGERPRINT }}
          script: |
            cd /home/Coffe-Vibra-Frontend
            git checkout index.html
            git pull origin main
            echo "¡Despliegue de Coffe completado!"